target/arc: implement basic SMP support
foss-for-synopsys-dwc-arc-processors/openocd pull request #57
Opened 2023-07-13 16:37 UTC by artemiy-volkov

This patch adds support for SMP targets in arc_poll(), arc_halt(), and arc_resume(), which is just enough to be able to use arc-openocd for simple program execution ('load_image' followed by 'resume $addr') in SMP mode. Other SMP-aware functionality (e.g. breakpoints, single-stepping, gdb support) are left to be implemented in the future.

This has been previously committed to the Zephyr project's openocd repo[1], and currently allows us to run nightly testsuite runs on real HW with arc-openocd as the program runner.

Included in this patch are also snps_hsdk_smp.cfg configuration files for the ARCv2 HSDK boards, which are functionally equivalent to their snps_hsdk.cfg counterparts except for the SMP target registration at the end.

[1] https://github.com/zephyrproject-rtos/openocd/pull/25

Change-Id: I04bef83b51dd1e5daee01b9c0392da5f16106468

2023-07-14 15:18 UTC, abrodkin requested changes
I suggest adding a separate configuration file for HSDK-4xD as it sports HS48 cores and its JTAG ID's differ from those on the original HSDK board.

See https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arc/hsdk4xd/support/openocd.cfg#L44:
```
set _TARGETNAME4 $_CHIPNAME.cpu4
jtag newtap $_CHIPNAME cpu4 -irlen 4 -ircapture 0x1 -expected-id 0x100c54b1
set _TARGETNAME3 $_CHIPNAME.cpu3
jtag newtap $_CHIPNAME cpu3 -irlen 4 -ircapture 0x1 -expected-id 0x100854b1
set _TARGETNAME2 $_CHIPNAME.cpu2
jtag newtap $_CHIPNAME cpu2 -irlen 4 -ircapture 0x1 -expected-id 0x100454b1
set _TARGETNAME1 $_CHIPNAME.cpu1
jtag newtap $_CHIPNAME cpu1 -irlen 4 -ircapture 0x1 -expected-id 0x100054b1
```

2023-07-14 15:54 UTC, artemiy-volkov commented
> I suggest adding a separate configuration file for HSDK-4xD as it sports HS48 cores and its JTAG ID's differ from those on the original HSDK board.
> 
> See https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arc/hsdk4xd/support/openocd.cfg#L44:
> 
> ```
> set _TARGETNAME4 $_CHIPNAME.cpu4
> jtag newtap $_CHIPNAME cpu4 -irlen 4 -ircapture 0x1 -expected-id 0x100c54b1
> set _TARGETNAME3 $_CHIPNAME.cpu3
> jtag newtap $_CHIPNAME cpu3 -irlen 4 -ircapture 0x1 -expected-id 0x100854b1
> set _TARGETNAME2 $_CHIPNAME.cpu2
> jtag newtap $_CHIPNAME cpu2 -irlen 4 -ircapture 0x1 -expected-id 0x100454b1
> set _TARGETNAME1 $_CHIPNAME.cpu1
> jtag newtap $_CHIPNAME cpu1 -irlen 4 -ircapture 0x1 -expected-id 0x100054b1
> ```

I will do that in a separate PR if you don't mind, as adding this .cfg file has no direct relation to the SMP support changes.

2023-07-14 15:56 UTC, abrodkin approved these changes
> I will do that in a separate PR if you don't mind, as adding this .cfg file has no direct relation to the SMP support changes.

That's fine! Let's go that way.

2023-07-18 10:04 UTC, EvgeniiDidin approved these changes
Looks good to me! Thank you!

2023-07-19 08:22 UTC, claziss approved these changes

2023-08-15 13:21 UTC, merged